-- CreateTable
CREATE TABLE `bus_vehicles` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `legacy_id` INTEGER NULL,
    `garage_number` VARCHAR(191) NOT NULL,
    `registration_number` VARCHAR(191) NULL,
    `vehicle_number` VARCHAR(191) NULL,
    `vehicle_type` INTEGER NULL,
    `vehicle_brand` INTEGER NULL,
    `vehicle_model` INTEGER NULL,
    `chassis_number` VARCHAR(50) NULL,
    `motor_number` VARCHAR(50) NULL,
    `year_of_manufacture` DATETIME(3) NULL,
    `seat_capacity` INTEGER NOT NULL DEFAULT 0,
    `standing_capacity` INTEGER NOT NULL DEFAULT 0,
    `total_capacity` INTEGER NOT NULL DEFAULT 0,
    `fuel_type` INTEGER NULL,
    `active` BOOLEAN NOT NULL DEFAULT true,
    `visible` BOOLEAN NOT NULL DEFAULT true,
    `wifi` BOOLEAN NOT NULL DEFAULT false,
    `air_condition` BOOLEAN NOT NULL DEFAULT false,
    `ramp_for_disabled` BOOLEAN NOT NULL DEFAULT false,
    `video_system` BOOLEAN NOT NULL DEFAULT false,
    `low_floor` BOOLEAN NOT NULL DEFAULT false,
    `imei` VARCHAR(20) NULL,
    `imei_net` VARCHAR(20) NULL,
    `gps_model` VARCHAR(100) NULL,
    `technical_control_from` DATETIME(3) NULL,
    `technical_control_to` DATETIME(3) NULL,
    `registration_valid_to` DATETIME(3) NULL,
    `first_registration_date` DATETIME(3) NULL,
    `central_point_id` INTEGER NULL,
    `central_point_name` VARCHAR(200) NULL,
    `note` TEXT NULL,
    `image_url` VARCHAR(500) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `last_sync_at` DATETIME(3) NULL,

    UNIQUE INDEX `bus_vehicles_legacy_id_key`(`legacy_id`),
    UNIQUE INDEX `bus_vehicles_garage_number_key`(`garage_number`),
    INDEX `bus_vehicles_vehicle_type_idx`(`vehicle_type`),
    INDEX `bus_vehicles_active_idx`(`active`),
    INDEX `bus_vehicles_central_point_id_idx`(`central_point_id`),
    INDEX `bus_vehicles_legacy_id_idx`(`legacy_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
