version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smartcity-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: smartcity_dev
      MYSQL_USER: smartcity_user
      MYSQL_PASSWORD: SecurePassword123!
    ports:
      - "3325:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - smartcity-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: smartcity-redis
    restart: unless-stopped
    command: redis-server --requirepass RedisPassword123! --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - smartcity-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 3s
      retries: 5

networks:
  smartcity-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: