-- AlterTable price_table_groups: Change date_valid_from from DATE to VARCHAR(30)
ALTER TABLE `price_table_groups`
  MODIFY COLUMN `date_valid_from` VARCHAR(30) NOT NULL;

-- CreateEnum DirectionType
-- CreateEnum OnlineDiscountType

-- CreateTable lines
CREATE TABLE `lines` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `line_number` VARCHAR(5) NOT NULL,
    `actual_line_number` VARCHAR(10) NOT NULL,
    `line_title` VARCHAR(255) NOT NULL,
    `line_title_return` VARCHAR(255) NOT NULL,
    `root_line_number` VARCHAR(5) NOT NULL,
    `line_number_for_display` VARCHAR(20) NOT NULL,
    `circle_route` BOOLEAN NOT NULL DEFAULT false,
    `direction_id_for_display` ENUM('A', 'B') NOT NULL DEFAULT 'A',
    `line_title_for_display` VARCHAR(255) NOT NULL,
    `line_number_for_site` VARCHAR(255) NOT NULL,
    `furl` VARCHAR(255) NOT NULL,
    `to_place` VARCHAR(255) NOT NULL,
    `to_place_two` VARCHAR(255) NOT NULL,
    `num_of_direction` TINYINT NOT NULL DEFAULT 0,
    `official_departure` VARCHAR(30) NOT NULL,
    `date_valid_from` VARCHAR(30) NOT NULL,
    `price_table_ident` VARCHAR(64) NOT NULL,
    `monthly_price_table_ident` VARCHAR(64) NOT NULL,
    `subversion` VARCHAR(2) NOT NULL DEFAULT '0',
    `number_of_stations` SMALLINT NOT NULL DEFAULT 0,
    `vat_from_tax_table` VARCHAR(64) NOT NULL,
    `vat_id` VARCHAR(5) NOT NULL,
    `vat_value` VARCHAR(5) NOT NULL,
    `discount_tariff_table_ident` VARCHAR(50) NOT NULL,
    `region_table_ident` VARCHAR(50) NOT NULL,
    `zone_table_ident` VARCHAR(50) NOT NULL,
    `distance_table_ident` VARCHAR(50) NOT NULL,
    `cities_table_ident` VARCHAR(50) NOT NULL,
    `line_type_id` SMALLINT NOT NULL DEFAULT 0,
    `line_type` VARCHAR(100) NOT NULL DEFAULT 'none',
    `changed_since_sync` VARCHAR(2) NOT NULL DEFAULT '0',
    `change_log` LONGTEXT NOT NULL DEFAULT (''),
    `change_incremental` VARCHAR(5) NOT NULL DEFAULT '0',
    `central_point_db_id` VARCHAR(10) NOT NULL DEFAULT '0',
    `central_point_name` VARCHAR(200) NOT NULL,
    `changed_by` VARCHAR(50) NOT NULL,
    `date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `status` VARCHAR(8) NOT NULL DEFAULT 'N',
    `bus_operator` SMALLINT NOT NULL DEFAULT 0,
    `display_by_dispach_planning` BOOLEAN NOT NULL DEFAULT false,
    `line_route` LONGTEXT NOT NULL DEFAULT (''),
    `line_route1` LONGTEXT NOT NULL DEFAULT (''),
    `bestfrom` DATE NULL,
    `g_line_route` LONGTEXT NOT NULL DEFAULT (''),
    `g_line_route1` LONGTEXT NOT NULL DEFAULT (''),
    `max_speed` TINYINT NOT NULL DEFAULT 0,
    `time_allowed` SMALLINT NOT NULL DEFAULT 0,
    `isolated_exports_accounting_software` BOOLEAN NOT NULL DEFAULT false,
    `days_sell_in_advance` SMALLINT NOT NULL DEFAULT 255,
    `round_price` MEDIUMINT NOT NULL DEFAULT 500,
    `best_from_ret` DATE NOT NULL DEFAULT '2012-01-01',
    `days_sell_in_advance_ret` SMALLINT NOT NULL DEFAULT 255,
    `best_to` DATE NOT NULL DEFAULT '2029-12-31',
    `best_to_ret` DATE NOT NULL DEFAULT '2029-12-31',
    `check_in_amount` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    `price_per_km` DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    `additional_line_type_id` TINYINT NOT NULL DEFAULT 0,
    `used_in_dispech` BOOLEAN NOT NULL DEFAULT false,
    `show_on_net` BOOLEAN NOT NULL DEFAULT false,
    `show_on_net_city` BOOLEAN NOT NULL DEFAULT false,
    `net_pricelist_id` INTEGER NOT NULL DEFAULT 0,
    `PAY_ON_DELIVERY` VARCHAR(50) NOT NULL,
    `MOBILE_PHONE` VARCHAR(50) NOT NULL,
    `CREDIT_CARD` VARCHAR(50) NOT NULL,
    `used_in_booking` BOOLEAN NOT NULL DEFAULT false,
    `start_terminus_km` DECIMAL(8, 3) NULL DEFAULT 0.000,
    `end_terminus_km` DECIMAL(8, 3) NULL DEFAULT 0.000,
    `rv_sale_flag` BOOLEAN NULL DEFAULT false,
    `rv_line_source` TINYINT NOT NULL DEFAULT 3,
    `qr_validations` INTEGER NOT NULL DEFAULT 0,
    `qr_validations_return` INTEGER NOT NULL DEFAULT 0,
    `qr_validations_dir1` INTEGER NOT NULL DEFAULT 0,
    `qr_validations_return_dir1` INTEGER NOT NULL DEFAULT 0,
    `transient_price_setting` INTEGER NOT NULL DEFAULT 0,
    `sell_without_seat_no` BOOLEAN NOT NULL DEFAULT true,
    `always_export_flag` BOOLEAN NOT NULL DEFAULT false,
    `min_mode_security` INTEGER NOT NULL DEFAULT 60,
    `allowed_min` INTEGER NOT NULL DEFAULT 240,
    `main_line_from_group` VARCHAR(50) NOT NULL,
    `route_code` VARCHAR(10) NOT NULL,
    `gtfs_route_id` INTEGER NOT NULL DEFAULT 0,
    `price_variation_id` INTEGER NOT NULL DEFAULT 0,
    `wrong_direction_type` INTEGER NULL DEFAULT 0,
    `gtfs_shape_id` VARCHAR(50) NOT NULL,
    `description_of_streets_gtfs` VARCHAR(1255) NOT NULL,
    `used_in_date_shedule` BOOLEAN NOT NULL DEFAULT false,
    `line_km_mean_value_with_bus_terminus` DECIMAL(8, 3) NULL DEFAULT 0.000,
    `system_types_id` INTEGER NOT NULL,
    `categories_line_id` INTEGER NOT NULL,
    `time_from_by_line` TIME NOT NULL DEFAULT '00:00:00',
    `time_to_by_line` TIME NOT NULL DEFAULT '23:59:59',
    `online_discount_type` ENUM('0', '1', '2') NOT NULL DEFAULT '0',
    `show_on_web` BOOLEAN NOT NULL DEFAULT false,
    `updated_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `show_on_android` BOOLEAN NOT NULL DEFAULT true,
    `legacy_ticketing_id` BIGINT NULL,
    `legacy_city_id` BIGINT NULL,

    UNIQUE INDEX `lines_price_table_ident_key`(`price_table_ident`),
    UNIQUE INDEX `lines_legacy_ticketing_id_key`(`legacy_ticketing_id`),
    UNIQUE INDEX `lines_legacy_city_id_key`(`legacy_city_id`),
    INDEX `idx_line_number`(`line_number`),
    INDEX `idx_line_number_for_display`(`line_number_for_display`),
    INDEX `idx_date_valid_from`(`date_valid_from`),
    INDEX `idx_status`(`status`),
    INDEX `idx_central_point_db_id`(`central_point_db_id`),
    INDEX `idx_line_type`(`line_type`),
    INDEX `idx_line_type_id`(`line_type_id`),
    INDEX `idx_bus_operator`(`bus_operator`),
    INDEX `idx_isolated_exports`(`isolated_exports_accounting_software`),
    INDEX `idx_gtfs_route_id`(`gtfs_route_id`),
    INDEX `idx_price_variation_id`(`price_variation_id`),
    INDEX `idx_legacy_ticketing_id`(`legacy_ticketing_id`),
    INDEX `idx_legacy_city_id`(`legacy_city_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `lines` ADD CONSTRAINT `lines_date_valid_from_fkey` FOREIGN KEY (`date_valid_from`) REFERENCES `price_table_groups`(`date_valid_from`) ON DELETE RESTRICT ON UPDATE CASCADE;
