spec_version: 1
name: smart-city-backend
region: fra
services:
  - name: api
    dockerfile_path: apps/backend/Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_USERNAME/smart-city
    http_port: 3010
    instance_count: 1
    instance_size_slug: professional-xs
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    envs:
      # Database connection
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      # Redis connection
      - key: REDIS_HOST
        scope: RUN_TIME
        value: ${redis.HOSTNAME}
      - key: REDIS_PORT
        scope: RUN_TIME
        value: ${redis.PORT}
      - key: REDIS_PASSWORD
        scope: RUN_TIME
        value: ${redis.PASSWORD}
      # JWT Secrets
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      # Environment
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3010"
      # CORS
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "https://admin.smart-city.rs,https://app.smart-city.rs"
    cors:
      allow_origins:
        - exact: https://admin.smart-city.rs
        - exact: https://app.smart-city.rs
      allow_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allow_headers:
        - content-type
        - authorization
      allow_credentials: true

databases:
  - name: mysql-cluster
    engine: MYSQL
    production: true
    cluster_name: smart-city-mysql
    version: "8"
    size: db-s-1vcpu-1gb
    num_nodes: 1
  
  - name: redis
    engine: REDIS
    production: true
    cluster_name: smart-city-redis
    version: "7"
    size: db-s-1vcpu-1gb
    num_nodes: 1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
  - rule: CPU_UTILIZATION
    value: 85
    window: FIVE_MINUTES
  - rule: MEM_UTILIZATION
    value: 85
    window: FIVE_MINUTES
  - rule: DOWNTIME
    value: 5
    window: FIVE_MINUTES