export type MeasuringPoints = {
  IDMM: number;
  datum_ugradnje?: string | null;
  adresa: string;
  ulaz: string;
  broj: string;
  prosekPS: number;
  napomena: string;
  broj_clanova_KS: number;
  broj_potrosaca_KS: number;
  korektivno: number;
  virtuelno: number;
  kontrolno: number;
  prosekU: number;
  primMM: string;
  redosledMM: number;
  naselje: string;
  IDU: number;
  broj2: number;
  checkLL: string;
  latitude: number;
  longtitude: number;
  KS: number;
  _NapomenaMM: string;
  prosekO: number;
  status: number;
  type_id: number;
};
