import {
  IsInt,
  IsString,
  IsOptional,
  IsBoolean,
  IsEnum,
} from 'class-validator';
import { Type, Transform } from 'class-transformer';
import { ApiPropertyOptional } from '@nestjs/swagger';
import { DayOfWeek } from './create-turnus-default.dto';

export class FindTurnusDefaultsDto {
  @ApiPropertyOptional({
    description: 'ID vozača',
    example: 1,
  })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  driverId?: number;

  @ApiPropertyOptional({
    description: 'Naziv turnusa',
    example: '00018-1',
  })
  @IsOptional()
  @IsString()
  turnusName?: string;

  @ApiPropertyOptional({
    description: 'Broj linije',
    example: '18',
  })
  @IsOptional()
  @IsString()
  lineNumberForDisplay?: string;

  @ApiPropertyOptional({
    description: 'Broj smene',
    example: 1,
  })
  @IsOptional()
  @IsInt()
  @Type(() => Number)
  shiftNumber?: number;

  @ApiPropertyOptional({
    description: 'Dan u nedelji',
    enum: DayOfWeek,
  })
  @IsOptional()
  @IsEnum(DayOfWeek)
  dayOfWeek?: DayOfWeek;

  @ApiPropertyOptional({
    description: 'Samo aktivni defaults',
    example: true,
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  @Transform(({ value }) => value === 'true' || value === true)
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'Samo auto-generisani defaults',
    example: false,
  })
  @IsOptional()
  @IsBoolean()
  @Transform(({ value }) => value === 'true' || value === true)
  autoGenerated?: boolean;
}
