-- CreateTable
-- Kreiranje date_travel_order tabele (identična legacy strukturi)
CREATE TABLE `date_travel_order` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `line_type` VARCHAR(30) NOT NULL,
    `start_date` DATE NOT NULL,
    `driver_id` INTEGER UNSIGNED NOT NULL,
    `driver_name` VARCHAR(50) NOT NULL,
    `other_ids` INTEGER UNSIGNED NOT NULL,
    `other_names` VARCHAR(50) NOT NULL,
    `other_ids_2` INTEGER UNSIGNED NOT NULL,
    `other_names_2` VARCHAR(50) NOT NULL,
    `line_no` VARCHAR(6) NOT NULL,
    `line_name` VARCHAR(80) NOT NULL,
    `bus_name` VARCHAR(50) NOT NULL,
    `no_of_seats` SMALLINT UNSIGNED NOT NULL,
    `garage_no` VARCHAR(20) NOT NULL,
    `regist_no` VARCHAR(20) NOT NULL,
    `regist_area` VARCHAR(30) NOT NULL,
    `bpiv_date` DATE NOT NULL,
    `bpiv_no` VARCHAR(30) NOT NULL,
    `start_time` TIME(0) NOT NULL,
    `end_time` TIME(0) NOT NULL,
    `end_date` DATE NOT NULL,
    `end_time_found` TIME(0) NOT NULL,
    `end_time_manual` TIME(0) NOT NULL,
    `end_date_found` DATE NOT NULL,
    `order_no` INTEGER UNSIGNED NOT NULL,
    `issuedate` DATE NOT NULL,
    `planned` TINYINT UNSIGNED NOT NULL,
    `realised` TINYINT UNSIGNED NOT NULL,
    `comment` TEXT NOT NULL,
    `prepare_time` VARCHAR(5) NOT NULL,
    `line_time` VARCHAR(5) NOT NULL,
    `line_km` DECIMAL(8, 3) NOT NULL,
    `speed_limit` TINYINT NOT NULL,
    `check_cash` TINYINT NOT NULL,
    `check_km` TINYINT NOT NULL,
    `check_prepare` TINYINT NOT NULL,
    `check_speed` TINYINT NOT NULL,
    `check_start` TINYINT NOT NULL,
    `check_end` TINYINT NOT NULL,
    `check_stations` TINYINT NOT NULL,
    `check_route` TINYINT NOT NULL,
    `check_rpm` TINYINT NOT NULL,
    `check_acc_brk` TINYINT NOT NULL,
    `check_mud` TINYINT UNSIGNED NOT NULL,
    `check_fuel` TINYINT UNSIGNED NOT NULL,
    `check_fuel_time` DATETIME(0) NOT NULL,
    `km_found` DECIMAL(8, 3) NOT NULL,
    `prepare_found` VARCHAR(5) NOT NULL,
    `speed_peak_found` TINYINT NOT NULL,
    `speed_average_found` DECIMAL(5, 2) NOT NULL,
    `speed_duration_found` VARCHAR(5) NOT NULL,
    `speed_allowed_peak` TINYINT NOT NULL,
    `speed_allowed_duration` VARCHAR(5) NOT NULL,
    `speedreg_peak_found` TINYINT NOT NULL,
    `speedreg_average_found` DECIMAL(5, 2) NOT NULL,
    `speedreg_duration_found` VARCHAR(5) NOT NULL,
    `speedreg_allowed_peak` TINYINT NOT NULL,
    `speedreg_allowed_duration` VARCHAR(5) NOT NULL,
    `speedred_peak_found` TINYINT NOT NULL,
    `speedred_average_found` DECIMAL(5, 2) NOT NULL,
    `speedred_duration_found` VARCHAR(5) NOT NULL,
    `speedred_allowed_peak` TINYINT NOT NULL,
    `speedred_allowed_duration` VARCHAR(5) NOT NULL,
    `reduction_road_found` TINYINT NOT NULL,
    `reduction_km_found` DECIMAL(8, 3) NOT NULL,
    `temp_average_found` TINYINT UNSIGNED NOT NULL,
    `temp_peak_found` TINYINT UNSIGNED NOT NULL,
    `oil_average_found` SMALLINT UNSIGNED NOT NULL,
    `oil_peak_found` SMALLINT UNSIGNED NOT NULL,
    `start_found` TIME(0) NOT NULL,
    `start_date_found` DATE NOT NULL,
    `start_date_manual` DATE NOT NULL,
    `end_date_manual` DATE NOT NULL,
    `start_manual` TIME(0) NOT NULL,
    `start_reason` TINYINT NOT NULL,
    `stations_found` TINYINT NOT NULL,
    `cash_comment` TEXT NOT NULL,
    `km_comment` TEXT NOT NULL,
    `prepare_comment` TEXT NOT NULL,
    `speed_comment` TEXT NOT NULL,
    `start_comment` TEXT NOT NULL,
    `end_comment` TEXT NOT NULL,
    `route_comment` TEXT NOT NULL,
    `gas_found` VARCHAR(11) NOT NULL,
    `fisc_info` VARCHAR(40) NOT NULL,
    `temp_comment` TEXT NOT NULL,
    `oil_comment` TEXT NOT NULL,
    `edited_by` INTEGER NOT NULL,
    `before_time` VARCHAR(5) NOT NULL,
    `after_time` VARCHAR(5) NOT NULL,
    `before_time_found` VARCHAR(8) NOT NULL,
    `after_time_found` VARCHAR(8) NOT NULL,
    `shedule_id` INTEGER NOT NULL,
    `prepare_flag` VARCHAR(1) NOT NULL,
    `before_flag` VARCHAR(1) NOT NULL,
    `duration_flag` VARCHAR(1) NOT NULL,
    `after_flag` VARCHAR(1) NOT NULL,
    `rpm_found` VARCHAR(30) NOT NULL,
    `acc_brk_found` VARCHAR(30) NOT NULL,
    `addit_opt_found` MEDIUMINT UNSIGNED NOT NULL,
    `fuel_cons_prep` DECIMAL(6, 2) NOT NULL,
    `fuel_cons_before` DECIMAL(6, 2) NOT NULL,
    `fuel_cons_after` DECIMAL(6, 2) NOT NULL,
    `fuel_cons_main` DECIMAL(6, 2) NOT NULL,
    `fuel_cons_stop` DECIMAL(6, 2) NOT NULL,
    `speed_b_chk` TINYINT UNSIGNED NOT NULL,
    `speed_b_val` DECIMAL(5, 2) NOT NULL,
    `rpm_b_chk` TINYINT UNSIGNED NOT NULL,
    `rpm_b_val` DECIMAL(5, 2) NOT NULL,
    `accbrk_b_chk` TINYINT UNSIGNED NOT NULL,
    `accbrk_b_val` DECIMAL(5, 2) NOT NULL,
    `all_b_chk` TINYINT UNSIGNED NOT NULL,
    `all_b_val` DECIMAL(5, 2) NOT NULL,
    `modified_by` INTEGER UNSIGNED NOT NULL,
    `modified_date` DATETIME(0) NOT NULL,
    `created_by` INTEGER NOT NULL,
    `created_date` DATETIME(0) NOT NULL,
    `realised_by` INTEGER NOT NULL,
    `realised_date` DATETIME(0) NOT NULL,
    `canceled_by` INTEGER NOT NULL,
    `canceled_date` DATETIME(0) NOT NULL,
    `like_planned_by` INTEGER NOT NULL,
    `like_planned_date` DATETIME(0) NOT NULL,
    `missing_gps_data_percent` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `km_found_by_analyse` DECIMAL(8, 3) NOT NULL DEFAULT 0,
    `stations_found_by_analyse` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    `stations_stopped` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    `vehicle_age` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `vehicle_age_months` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `vehicle_age_days` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `transportation_cost` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `first_3_last_3_departure` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `cp_realised` SMALLINT UNSIGNED NOT NULL DEFAULT 0,

    INDEX `garage_no`(`garage_no`),
    INDEX `driver_id`(`driver_id`),
    INDEX `order_no`(`order_no`),
    INDEX `shedule_id`(`shedule_id`),
    INDEX `realised_by`(`realised_by`),
    INDEX `realised_date`(`realised_date`),
    PRIMARY KEY (`id`, `start_date`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
