-- CreateTable
CREATE TABLE IF NOT EXISTS `date_shedule` (
  `start_time` time NOT NULL COMMENT 'start time from timetable (may not be actual start time if departure is split into 2 or more departures, in that case, actual start time is in field tt_start_time)',
  `start_station` varchar(50) NOT NULL COMMENT 'start station name',
  `end_time` time NOT NULL COMMENT 'end time (may not be end time from timetable if departure is split into two or more departures)',
  `end_station` varchar(50) NOT NULL COMMENT 'end station name',
  `line_no` varchar(6) NOT NULL COMMENT 'line number',
  `line_name` varchar(100) NOT NULL COMMENT 'line name',
  `bus_operator` varchar(40) NOT NULL COMMENT 'name of bus operator',
  `bus_number` smallint(2) unsigned NOT NULL COMMENT 'bus number on same departure, same line number, same time, same direction',
  `bus_registration` varchar(10) NOT NULL COMMENT 'vehicle plate number',
  `bus_garage_no` varchar(15) NOT NULL COMMENT 'vehicle garage number',
  `peron` varchar(4) NOT NULL COMMENT 'landplace number',
  `assigned_persons` varchar(500) NOT NULL COMMENT 'assigned persons roles and names imploded using |$| string',
  `r_bus_registration` varchar(10) NOT NULL COMMENT 'realised bus registration',
  `r_bus_garage_no` varchar(15) NOT NULL COMMENT 'realised bus garage number',
  `r_peron` varchar(4) NOT NULL COMMENT 'realised landplace',
  `r_assigned_persons` varchar(500) NOT NULL COMMENT 'realised assigned persons roles and names imploded using |$| string',
  `r_user_ids` varchar(500) NOT NULL COMMENT 'realised user ids and events, for format see user_ids field',
  `user_1_id_realised` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `user_2_id_realised` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `user_3_id_realised` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `status` smallint(3) unsigned NOT NULL COMMENT 'deprecated',
  `start_date` date NOT NULL COMMENT 'start date of departure, see start_time',
  `user_ids` varchar(500) NOT NULL COMMENT 'Assigned user ids and events, imploded using string |$|. After explode we have one string for each user. This user string is imploded using ||| string. After explode of one user string we end up with array of strings. In this array, first item is user ID, second item is user group ID from user_groups table (driver=2 for example), third item is user events for day 0, fourth item is user events for day 1 (for multi day departures) etc. If there is no fourth item, then there is no day 1. User events string is imploded using |#| string. After explode we have array of events-times pairs strings. Each event-time string is imploded using ### string. After explode of event-time string we have array with two strings, event ID from changes_codes table and event time.',
  `user_1_id_planned` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `user_2_id_planned` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `user_3_id_planned` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `bus_reg_2` varchar(10) NOT NULL COMMENT 'deprecated',
  `bus_gar_2` varchar(10) NOT NULL COMMENT 'deprecated',
  `end_date` date NOT NULL COMMENT 'actual end date of departure',
  `direction` tinyint(1) unsigned NOT NULL COMMENT 'line number direction (0=from first to last station direction, 1=from last to first station direction)',
  `ride_type` tinyint(1) unsigned NOT NULL COMMENT '0=normal ride, 1=free ride (slobodna voznja) , 2=extra ride (vanredna voznja) ,9=KM ride (voznja po KM)',
  `free_id` mediumint(5) unsigned NOT NULL DEFAULT '0' COMMENT 'free ride id from date_free_ride table',
  `km_pred` decimal(8,3) unsigned NOT NULL DEFAULT '0.000' COMMENT 'predicted KM for line number',
  `km_real` decimal(8,3) unsigned NOT NULL DEFAULT '0.000' COMMENT 'deprecated',
  `line_type` varchar(40) NOT NULL DEFAULT '' COMMENT 'line type string from line_types table',
  `tour_id` mediumint(8) unsigned NOT NULL DEFAULT '0' COMMENT 'id of turnus from changes_codes_tours table in which this departure is assigned',
  `central_point` smallint(4) unsigned NOT NULL DEFAULT '0' COMMENT 'central point id from central_points table',
  `modified` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0=not split, > 0 = split departure',
  `id` int(12) unsigned NOT NULL AUTO_INCREMENT,
  `tt_start_time` time NOT NULL DEFAULT '00:00:00' COMMENT 'actual start time',
  `tt_start_date` date NOT NULL COMMENT 'actual start date',
  `price_tables_index_id` int(12) unsigned NOT NULL DEFAULT '0',
  `departure_open_time` datetime NOT NULL,
  `departure_close_time` datetime NOT NULL,
  `start_station_uid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `end_station_uid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `last_station_update_time` datetime NOT NULL,
  `last_station_number` smallint(5) unsigned NOT NULL DEFAULT '0',
  `number_of_stations_found` smallint(5) unsigned NOT NULL DEFAULT '0',
  `number_of_stations_in_line` smallint(5) unsigned NOT NULL DEFAULT '0',
  `current_route_position` smallint(5) unsigned NOT NULL DEFAULT '0',
  `first_station_time` datetime NOT NULL,
  `last_station_time` datetime NOT NULL,
  `android_departure_id` int(12) unsigned NOT NULL DEFAULT '0',
  `android_departure_id_close` int(12) unsigned NOT NULL DEFAULT '0',
  `turnus_departure_no` smallint(5) unsigned NOT NULL DEFAULT '0',
  `turnus_vehicle_no` smallint(5) unsigned NOT NULL DEFAULT '0',
  `next_departure_time` time NOT NULL DEFAULT '00:00:00',
  `departure_status` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `departure_analysed` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `departure_analysed_datetime` datetime DEFAULT NULL,
  `vehicle_group_types_id` smallint(5) unsigned DEFAULT '0',
  `vremena_polaska_st_id` int(12) unsigned NOT NULL DEFAULT '0',
  `planned_by` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0-automatic; 1-dispatcher;',
  `last_modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`start_date`),
  KEY `free_id` (`free_id`),
  KEY `end_date` (`end_date`),
  KEY `start_date` (`start_date`,`start_time`) USING BTREE,
  KEY `android_departure_id` (`android_departure_id`),
  KEY `price_tables_index_id_index` (`price_tables_index_id`),
  KEY `start_date2` (`start_date`,`tour_id`),
  KEY `last_modified` (`last_modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Imported from legacy BGNaplata server - main ticketing schedule table';
