-- CreateTable
CREATE TABLE `changes_codes_tours` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `turnus_id` MEDIUMINT UNSIGNED NOT NULL,
    `turnus_name` VARCHAR(320) NOT NULL,
    `line_no` VARCHAR(6) NOT NULL,
    `start_time` TIME(0) NOT NULL,
    `direction` TINYINT NOT NULL,
    `duration` TIME(0) NOT NULL,
    `central_point` VARCHAR(4) NOT NULL,
    `change_code` INTEGER NOT NULL,
    `job_id` SMALLINT NOT NULL,
    `new_start_time` TIME(0) NOT NULL,
    `new_duration` TIME(0) NOT NULL,
    `start_station` SMALLINT NOT NULL,
    `end_station` SMALLINT NOT NULL,
    `day_number` TINYINT NOT NULL,
    `line_type_id` TINYINT NOT NULL,
    `rezijski` VARCHAR(20) NOT NULL,
    `print_id` VARCHAR(4) NOT NULL,
    `between_rez` TINYINT UNSIGNED NOT NULL,
    `bus_number` TINYINT UNSIGNED NOT NULL DEFAULT 1,
    `start_station_id` MEDIUMINT UNSIGNED NOT NULL,
    `end_station_id` MEDIUMINT UNSIGNED NOT NULL,
    `change_time` DATETIME(0) NOT NULL,
    `change_user` VARCHAR(8) NOT NULL,
    `active` TINYINT UNSIGNED NOT NULL,
    `first_day_duration_part` TIME(0) NOT NULL,
    `second_day_duration_part` TIME(0) NOT NULL,
    `custom_id` VARCHAR(20) NOT NULL,
    `transport_id` VARCHAR(20) NOT NULL,
    `departure_number` TINYINT UNSIGNED NOT NULL,
    `shift_number` TINYINT UNSIGNED NOT NULL,
    `turage_no` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `departure_no_in_turage` TINYINT UNSIGNED NOT NULL,

    INDEX `turnus_id`(`turnus_id` ASC),
    INDEX `line_type_id`(`line_type_id` ASC),
    INDEX `central_point`(`central_point` ASC),
    INDEX `turnus_name`(`turnus_name` ASC),
    INDEX `line_no`(`line_no` ASC),
    INDEX `change_code`(`change_code` ASC),
    INDEX `start_time`(`start_time` ASC),
    INDEX `testaca`(`central_point` ASC, `turnus_name` ASC),
    INDEX `turnus_id_2`(`turnus_id` ASC, `turnus_name` ASC),
    INDEX `line_no2`(`line_no` ASC, `direction` ASC, `start_time` ASC),
    PRIMARY KEY (`id` ASC)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB;
