-- CreateTable
CREATE TABLE `central_points` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `cp_name` VARCHAR(400) NOT NULL,
    `cp_address` VARCHAR(400) NOT NULL,
    `cp_zip` VARCHAR(10) NOT NULL,
    `cp_city` VARCHAR(100) NOT NULL,
    `cp_phone1` VARCHAR(50) NOT NULL,
    `cp_phone2` VARCHAR(50) NOT NULL,
    `cp_email` VARCHAR(255) NOT NULL,
    `cp_boss` VARCHAR(200) NOT NULL,
    `cp_boss_phone` VARCHAR(50) NOT NULL,
    `cp_boss_email` VARCHAR(255) NOT NULL,
    `main_station_uid` VARCHAR(6) NOT NULL,
    `cp_longitude` VARCHAR(50) NOT NULL,
    `cp_latitude` VARCHAR(50) NOT NULL,
    `cp_comment` VARCHAR(400) NOT NULL,
    `cp_owes` FLOAT NOT NULL,
    `cp_expects` FLOAT NOT NULL,
    `cp_saldo` FLOAT NOT NULL,
    `income_settlement_timeframe_cp` VARCHAR(10) NOT NULL DEFAULT '0',
    `changed_by` VARCHAR(100) NOT NULL,
    `date_time` DATETIME(0) NOT NULL,
    `enablejavaapplet` BOOLEAN NOT NULL DEFAULT false,
    `enableticketreturn` SMALLINT NOT NULL DEFAULT 0,
    `enableticketdelete` BOOLEAN NOT NULL DEFAULT false,
    `enableotherticketscheck` BOOLEAN NOT NULL DEFAULT true,
    `enablejournalcheck` TINYINT NOT NULL DEFAULT 1,
    `internal_fuel` BOOLEAN NULL,
    `cp_color` VARCHAR(7) NOT NULL,
    `cp_line_color` VARCHAR(7) NOT NULL,
    `cp_image` MEDIUMBLOB NULL,
    `cp_image_android` MEDIUMBLOB NULL,
    `cp_customer_info_close_departure` MEDIUMBLOB NULL,
    `cp_customer_info_open_departure` MEDIUMBLOB NULL,
    `cp_validator_close_departure` MEDIUMBLOB NULL,
    `cp_validator_open_departure` MEDIUMBLOB NULL,
    `send_android_pin_request_to_admin` TINYINT NOT NULL DEFAULT 0,
    `android_admin` BIGINT NOT NULL DEFAULT 0,
    `cp_country_id` INTEGER NOT NULL DEFAULT 0,
    `cp_country_name` VARCHAR(50) NULL,
    `cp_vat_id` VARCHAR(15) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `other_cp_view` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `dispatch_order_by_cp` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `active` BOOLEAN NOT NULL DEFAULT false,
    `place_of_the_invoice` VARCHAR(100) NULL,
    `current_account` VARCHAR(100) NULL,
    `current_account_for_plastic` VARCHAR(100) NULL,
    `depot_code` VARCHAR(20) NULL,
    `creating_zip_by_gtfs_starndard` BOOLEAN NOT NULL DEFAULT false,
    `default_device_list_subgroup_id` INTEGER NULL,

    INDEX `central_points_main_station_uid_idx`(`main_station_uid`),
    INDEX `central_points_active_idx`(`active`),
    INDEX `central_points_depot_code_idx`(`depot_code`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

